#!C:\Users\prasa\Desktop\End_to_end_fraud\Fraud_detection_end_to_end_project\ml_env\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
